#!/bin/sh
# Setup translation fetching during development

# Stop on errors
set -e

cd "$(dirname "$0")/.."

./node_modules/.bin/gulp setup-and-fetch-nightly-translations
#/home/vscode/.nvm/versions/node/v24.15.0/bin/gulp setup-and-fetch-nightly-translations
